INSERT INTO "tb_locations_departaments" VALUES('91', 'AMAZONAS');
INSERT INTO "tb_locations_departaments" VALUES('05', 'ANTIOQUIA');
INSERT INTO "tb_locations_departaments" VALUES('81', 'ARAUCA');
INSERT INTO "tb_locations_departaments" VALUES('08', 'ATLÁNTICO');
INSERT INTO "tb_locations_departaments" VALUES('11', 'BOGOTÁ D.C.');
INSERT INTO "tb_locations_departaments" VALUES('13', 'BOLÍVAR');
INSERT INTO "tb_locations_departaments" VALUES('15', 'BOYACÁ');
INSERT INTO "tb_locations_departaments" VALUES('17', 'CALDAS');
INSERT INTO "tb_locations_departaments" VALUES('18', 'CAQUETÁ');
INSERT INTO "tb_locations_departaments" VALUES('85', 'CASANARE');
INSERT INTO "tb_locations_departaments" VALUES('19', 'CAUCA');
INSERT INTO "tb_locations_departaments" VALUES('20', 'CESAR');
INSERT INTO "tb_locations_departaments" VALUES('27', 'CHOCÓ');
INSERT INTO "tb_locations_departaments" VALUES('23', 'CÓRDOBA');
INSERT INTO "tb_locations_departaments" VALUES('25', 'CUNDINAMARCA');
INSERT INTO "tb_locations_departaments" VALUES('94', 'GUAINÍA');
INSERT INTO "tb_locations_departaments" VALUES('95', 'GUAVIARE');
INSERT INTO "tb_locations_departaments" VALUES('41', 'HUILA');
INSERT INTO "tb_locations_departaments" VALUES('44', 'LA GUAJIRA');
INSERT INTO "tb_locations_departaments" VALUES('47', 'MAGDALENA');
INSERT INTO "tb_locations_departaments" VALUES('50', 'META');
INSERT INTO "tb_locations_departaments" VALUES('52', 'NARIÑO');
INSERT INTO "tb_locations_departaments" VALUES('54', 'NORTE DE SANTANDER');
INSERT INTO "tb_locations_departaments" VALUES('86', 'PUTUMAYO');
INSERT INTO "tb_locations_departaments" VALUES('63', 'QUINDÍO');
INSERT INTO "tb_locations_departaments" VALUES('66', 'RISARALDA');
INSERT INTO "tb_locations_departaments" VALUES('88', 'SAN ANDRÉS');
INSERT INTO "tb_locations_departaments" VALUES('68', 'SANTANDER');
INSERT INTO "tb_locations_departaments" VALUES('70', 'SUCRE');
INSERT INTO "tb_locations_departaments" VALUES('73', 'TOLIMA');
INSERT INTO "tb_locations_departaments" VALUES('76', 'VALLE DEL CAUCA');
INSERT INTO "tb_locations_departaments" VALUES('97', 'VAUPÉS');
INSERT INTO "tb_locations_departaments" VALUES('99', 'VICHADA');
